---
title: "cmprsk"
author: "Magda Młynarczyk"
date: "17 maja 2017"
output: html_document
---

```{r}
library(dplyr)
library(stringr)
library(survival)
library(ggplot2)
library(cmprsk)

setwd("C:/Users/Magda/Desktop/magisterka/stare dane")
load("dane_obrobione.rda")

dt$status_infekcja <- as.numeric(dt$Infekcja)
dt$status_zgon <- as.numeric({dt$Infekcja == 0 & dt$Zgon == 1})
dt$czas <- ifelse(dt$Infekcja == 1, dt$`Cykl Vidazy przy infekcji`, dt$OS)
dt$status <- dt$status_infekcja+2*dt$status_zgon
colnames(dt)[which(colnames(dt) == "Rozpoznanie")] <- "rozpoznanie"
```

```{r}
ci <- cuminc(dt$czas, dt$status)
to_plot <- as.data.frame(cbind(ci[[1]][[1]], ci[[1]][[2]]))
to_plot$V3 <- rep(1, times = length(to_plot$V1))

to_plot <- rbind(to_plot, as.data.frame(cbind(ci[[2]][[1]], 
                       ci[[2]][[2]],
                       rep(2, times = length(ci[[2]][[1]]))
            )))

colnames(to_plot) <- c("czas", "prawdopodobieństwo zdarzenia", "status")
to_plot$status <- factor(to_plot$status)


to_plot$`prawdopodobieństwo przeżycia` <- sapply(to_plot$`prawdopodobieństwo zdarzenia`, function(x) 1-x)


ggplot(to_plot, aes(czas, `prawdopodobieństwo przeżycia`, color = status)) + 
    geom_step(size = 1) + 
    scale_y_continuous("Prawdopodobieństwo przeżycia", limits = c(0,1)) 


```

```{r}

lowerConf <- function(est, var){
    lowerConf <- exp(log(est) - 1.96*sqrt(var)/est)
}

upperConf <- function(est, var){
    upperCinf <- exp(log(est) + 1.96*sqrt(var)/est)
}

var1 <- ci[[1]][[3]]
var2 <- ci[[2]][[3]]
var <- c(var1, var2)

to_plot2 <- cbind(to_plot, var)

lower <- lowerConf(to_plot2$`prawdopodobieństwo przeżycia`, to_plot2$var)
upper <- upperConf(to_plot2$`prawdopodobieństwo przeżycia`, to_plot2$var)


ggplot(to_plot2, aes(czas, `prawdopodobieństwo przeżycia`, color = status)) + 
    geom_step(size = 1) + 
    scale_y_continuous("Prawdopodobieństwo przeżycia", limits = c(0,1)) +
    geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.3) +
    xlim(c(0,30))


```
czy to nam coś testuje?
```{r}
ci <- cuminc(dt$czas, dt$status==1, group = dt$rozpoznanie)

est <- c(0,0,0)
for(i in names(ci)[1:6]){
    x <- cbind(ci[[i]]$est, ci[[i]]$time, rep(i, times = length(ci[[i]]$est)))
    est <- rbind(est, x)
}
est <- as.data.frame(est)
est <- est[-1,]
colnames(est) <- c("cumulative incidence", "czas", "rozp")
est$`cumulative incidence` <- as.numeric(as.character(est$`cumulative incidence`))
est$czas <- as.numeric(as.character(est$czas))
est$rozp <- as.character(est$rozp)
est$grupa <- sapply(est$rozp, function(x) strsplit(x, " ")[[1]][1])
est$status <- sapply(est$rozp, function(x) strsplit(x, " ")[[1]][2])

#ggplot
ggplot(est, aes(czas, `cumulative incidence`, color = grupa)) + geom_step(size = 1) + facet_wrap(~status)+xlim(c(0,30))

y_min_AML1 <- lowerConf(ci[[1]]$est[which.max(ci[[1]]$time >12)-1], 
                                    ci[[1]]$var[which.max(ci[[1]]$time > 12)-1])
y_max_AML1 <- upperConf(ci[[1]]$est[which.max(ci[[1]]$time >12)-1], 
                                    ci[[1]]$var[which.max(ci[[1]]$time > 12)-1])


ggplot(est, aes(czas, `cumulative incidence`, color = grupa)) + 
    geom_step(size = 1) + 
    facet_wrap(~status)+xlim(c(0,30)) +
    geom_errorbar(aes(x = 12, ymin = y_min_AML1, ymax = y_max_AML1), color = "grey", size = 1) +
    
```

tylko znowu 9 obs dla cmml ze zgonem, trzeba porysować jak w survivalu
mamy p=value jak w survdiff


crr, ale brakuje p-value dla lrt chyba
```{r}
cov <- model.matrix(~dt$rozpoznanie)[,-1]
crr1 <- crr(dt$czas, dt$status, cov1 = cov, failcode = 1)
summary(crr1)

crr2 <- crr(dt$czas, dt$status, cov1 = cov, failcode = 2)
summary(crr2)

```
